---
- name: pulling docker image from the docker hub
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image from docker hub
      docker_image:
        name: chaithanya970/spe-mini:latest
        source: pull
    - name: start docker service
      service:
        name: docker
        state: started
    - name: running the container
      shell: docker run -it -d --name calculator chaithanya970/spe-mini:latest